name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: a4dj.exe
          path: a4dj.exe
          overwrite: 'true'

  release:
    name: release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: a4dj.exe
          path: bins
      - name: GitHub Release
        run: |
          gh release delete "${GITHUB_REF_NAME}" || true
          gh release create "${GITHUB_REF_NAME}" --repo ${{ github.repository }} --title "v${GITHUB_REF_NAME}" bins/a4dj.exe --notes "Automated release of v${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#      - name: Create GitHub Release
#        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
#        with:
#          files: bins/a4dj.exe
#          tag_name: ${{ github.ref_name }}
#          body: 'Automated release of ${{ github.ref_name }}.'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
